build: switch from npm to pnpm

diff --git a/Deploy b/Deploy
--- a/Deploy
+++ b/Deploy
@@ -1,15 +1,3 @@
 #!/bin/sh
 
-# Run npm only if package-lock.json changed
-old_sum=$(cat Deploy.cache)
-new_sum=$(md5sum package-lock.json)
-if [ "$old_sum" != "$new_sum" ]; then
-    npm ci --production=false
-    echo -n "$new_sum" > Deploy.cache
-fi
-
-npm run build
-
-# Reload the server
-rm -r sudoku/
-mv build/ sudoku/
+pnpm install && pnpm run build && rm -r sudoku/ && mv build/ sudoku/ && echo "Deployed" || echo "Error"
